---
name: Deploy webapp

env:
  ARTIFACT_NAME: csye7200-webapp.zip
  CODEDEPLOY_APPLICATION_NAME: csye7200-webapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye7200-webapp-deployment
  AWS_REGION: us-east-1

on:
  push:
    branches: [main]
jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
      with:
        ruby-version: 2.7.0

    - name: Build ARTIFACT
      run: |
        zip -r ${{env.ARTIFACT_NAME}} ./*
        mkdir cd_artifact
        mv ${{env.ARTIFACT_NAME}} cd_artifact/
        cd cd_artifact
        pwd
        ls -al
        cd ..
        pwd
        ls -al
    - name: AWS CREDENTIALS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
        aws-region: ${{env.AWS_REGION}}

    - name: Copy artifact to S3
      run: |
        aws s3 sync ./cd_artifact s3://${{secrets.S3_CODEDEPLOY_BUCKET}}

    - name: CodeDeploy API call
      run: |
        output=$(aws deploy create-deployment \
          --application-name ${{env.CODEDEPLOY_APPLICATION_NAME}} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{env.CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME}} \
          --description "CSYE7200 - CodeDeploy" \
          --s3-location bucket=${{secrets.S3_CODEDEPLOY_BUCKET}},key=${{env.ARTIFACT_NAME}},bundleType=zip \
          --region ${{env.AWS_REGION}} \
          --output json)

        echo $output

        dId=$(echo $output | jq -r '.deploymentId')

        aws deploy wait deployment-successful --deployment-id $dId