version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/webapp-install
hooks:
  BeforeInstall:
    - location: scripts/rails-stop.sh
      runas: root
      timeout: 60
  AfterInstall:
    - location: scripts/rails-install.sh
      runas: root
      timeout: 1200
  ApplicationStart:
    - location: scripts/rails-start.sh
      runas: root
      timeout: 60
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 300
      runas: root